version: '3.8'

networks:
 ams_network:
  driver: bridge

services:
  app:
    container_name: Admin2-Frontend
    image: admin2-frontend-image
    build:
      context: .
    ports:
      - 1574:80
    networks:
      - ams_network